package com.wscq.baseWeiChat.domain.repository;

import java.util.List;

/**
 * Created by zs on 16/9/19.
 */
public interface CrudMapper<T, ID> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    T selectByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T record);

    List<T> selectAll();
}
